### ISSUE TITLE
ConsoleHybridFlowWithPkce, API call fails due to Audience validation failure

### ISSUE THREAD

**Issue by stebueh** [IdentityServer/IdentityServer4.Samples#101]
Running the ConsoleHybridFlowWithPkce sample and using the access token against SampleApi fails:

    Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:1941/resources'. Did not match: validationParameters.ValidAudience: 'api1' or validationParameters.ValidAudiences: 'null'.
        at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
        at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
        at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()

I guess this has to do with the changes discussed in https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/36.

I could fix this in my local environment by not setting the `ApiName` and `ApiSecret` Properties of `IdentityServerAuthenticationOptions` in the SampleApi, yet I am unsure if this is the correct approach.

**Comment by leastprivilege** [comment]
i think this is fixed now
