### ISSUE TITLE
Call API using user token fails in Hybrid sample

### ISSUE THREAD

**Issue by Gentlehag** [IdentityServer/IdentityServer4.Samples#163]
When I start the projects hybrid sample  and I click on Call API using user token I get an unauthorized back.

> SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid': 'c6b7add7fda13a5746ffca33ca7c1376', 

I didn't make any changes to the code. just opened the  solution set multiple startup projects (api,identity,mvc) .

![image](https://cloud.githubusercontent.com/assets/4619513/25997051/a2b84ad4-371a-11e7-8a51-9d218f49377d.png)

In the log i can see:
```

Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware:Information: Failed to validate the token eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2YjdhZGQ3ZmRhMTNhNTc0NmZmY2EzM2NhN2MxMzc2IiwidHlwIjoiSldUIn0.eyJuYmYiOjE0OTQ1OTAwMzUsImV4cCI6MTQ5NDU5MzYzNSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6Im12YyIsInN1YiI6IjZlOTM2YzY0ZWM0OGNkMTM5YTU3YzAzN2ExNTNmYzhkZjM0OGZiYjg5N2Q1NGQ2YmJiMWFhMGY2MWM5MTJmNGQiLCJhdXRoX3RpbWUiOjE0OTQ1OTAwMzMsImlkcCI6Ikdvb2dsZSIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJhcGkxIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbImV4dGVybmFsIl19.ekDZ_5TafYHV-R6Yy7yJ4P5lk1sIakbaWddWRMkZ3PXRI0qDZIcT1HKqcNrVMUw9P3YV4OLIszUMIdNzXVLA3gI5sjTa3tLxwugsz12wcaLf-413dZRuE5slPJlcUsTP-DMnXI_P5yF6qV3vScWbZu46ZzoTQPI7KV4Ky-QKm5zypmubGQ-bzaC1uWQ0jpp5wgxmpCASSogh-KH2nhEkTKpznVASSPjdrH1XRYiJPT_YScGW5G7kFfEbzaCy9jn8Nb3SoWCN-zzT5uC5WPl133I3FS4aJe-g1Creh5I_LMsLZJD6X0aIS-Q-OyryGXTu_Zx4xELCXoaBcmfGQYv93A.

Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid': 'c6b7add7fda13a5746ffca33ca7c1376', 
token: '{"alg":"RS256","typ":"JWT","kid":"c6b7add7fda13a5746ffca33ca7c1376"}.{"nbf":1494590035,"exp":1494593635,"iss":"http://localhost:5000","aud":["http://localhost:5000/resources","api1"],"client_id":"mvc","sub":"6e936c64ec48cd139a57c037a153fc8df348fbb897d54d6bbb1aa0f61c912f4d","auth_time":1494590033,"idp":"Google","scope":["openid","profile","api1","offline_access"],"amr":["external"]}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware:Information: Bearer was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match 'kid': 'c6b7add7fda13a5746ffca33ca7c1376', 
token: '{"alg":"RS256","typ":"JWT","kid":"c6b7add7fda13a5746ffca33ca7c1376"}.{"nbf":1494590035,"exp":1494593635,"iss":"http://localhost:5000","aud":["http://localhost:5000/resources","api1"],"client_id":"mvc","sub":"6e936c64ec48cd139a57c037a153fc8df348fbb897d54d6bbb1aa0f61c912f4d","auth_time":1494590033,"idp":"Google","scope":["openid","profile","api1","offline_access"],"amr":["external"]}'.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed for user: (null).
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
```

**Comment by brockallen** [comment]
You're using temp key? I bet your IdSvr restarted, but the API has cached the old temp key.

**Comment by Gentlehag** [comment]
Over the time i restarted the solution many times. but always all runtimes together.
The Api only has a inmemory cache which should be cleared also by restart, right?

**Comment by Gentlehag** [comment]
i tested it on a secondary machine where it didn't run before. there it works. But how can i clean this state on the other machine?

**Comment by brockallen** [comment]
Any update?

**Comment by Rilton** [comment]
I managed to solve this issue while working on issue #161.

This was due to the way the authentication with Asp Identity was configured in conjunction with Identityserver 

Take a look into "dentityServer4-mongo-AspIdentity" sample at https://github.com/Rilton/IdentityServer4.Samples.Mongo

**Comment by Alxandr** [comment]
I have the exact same issue (which is fixed easily enough by clearing cookies), but shouldn't the oidc middleware check that the token is valid? It's kind of weird that I can browse around just fine, but the first time I try to use the access token (from JS) it fails with invalid token. Yet I've been using that token on the server all the time.

**Comment by leastprivilege** [comment]
The OIDC middleware (or rather the cookie MW) just provides an (too) easy way to store arbitrary stuff. That's all it does.
