### ISSUE TITLE
"Value cannot be null.\r\nParameter name: address"

### ISSUE THREAD

**Issue by dicksonkimeu** [IdentityServer/IdentityServer4.Samples#227]
{System.ArgumentNullException: Value cannot be null.
Parameter name: address
   at IdentityModel.Client.TokenClient..ctor(String address, HttpMessageHandler innerHttpMessageHandler)
   at IdentityModel.Client.TokenClient..ctor(String address, String clientId, String clientSecret, HttpMessageHandler innerHttpMessageHandler, AuthenticationStyle style)
   at IdentityModel.Client.TokenClient..ctor(String address, String clientId, String clientSecret, AuthenticationStyle style)
   at SalesLifeClient.Program.<MainAsync>d__1.MoveNext() in G:\IDClient\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SalesLifeClient.Program.Main(String[] args) in G:\IDClient\Program.cs:line 11}

**Comment by brockallen** [comment]
Perhaps provide some more context and details so we can know how to repro your issue?

**Comment by dicksonkimeu** [comment]
@brockallen am running the standard quick start samples provided.

1_ClientCredentials

**Comment by leastprivilege** [comment]
and whats the value of your address variable?

**Comment by dicksonkimeu** [comment]
Am just running the project. the default. localhost:5000 / 5001 / 5003 am just running the default start projects no editing

**Comment by leastprivilege** [comment]
Well . this is not answering my question. Maybe for some reason, your variable is null.

**Comment by dicksonkimeu** [comment]
Hello.

The address is null. Yet I have not edited the quick start sample codes.

**Comment by leastprivilege** [comment]
Then check the error property on the discovery response...

**Comment by dicksonkimeu** [comment]
![error](https://user-images.githubusercontent.com/4476822/32013625-58cde082-b9c4-11e7-8717-7efd0f699c4c.PNG)

**Comment by leastprivilege** [comment]
Not sure what you are trying to tell me tbh.

If disco.TokenEndpoint is null - check disco.Error to see if there is a problem.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
