### ISSUE TITLE
IdentityServer 4 using IIS

### ISSUE THREAD

**Issue by rodchenkov** [IdentityServer/IdentityServer4.Samples#23]
Hi All

I'm trying to run IdentityServer4.Samples using IIS and it is not working.
On localhost it works fine but using IIS not.

I already added question with info here
http://stackoverflow.com/questions/37257043/identityserver-4-using-iis

Can you please help me to find problem?

**Comment by leastprivilege** [comment]
Try again tomorrow or friday. We are currently updating everything to RC2

**Comment by digitarenet** [comment]
Also for me all work fine with localhost (IdServer and MVC App) but when I try to use IIS there are some problems...At this time, for test only, I'm using only one server where are configured IdServer that response on 1941 port and MVC app that response on port 3308... (I don't know if it is the right way?)

- **MVC App**  at x.x.x.x:3308: _seem to work correctly on IIS_;
- **IdServer** at x.x.x.x:1941: _when I try to access Secure Page from MVC app (http://x.x.x.x:3308/Home/Secure) or when I try to go to UI login page of the IdServ (http://x.x.x.x:1941/ui/login) this error occour_:

```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:

~/UI/Home/Views/Index.cshtml
~/UI/SharedViews/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
...
```

Instead, working locally, on localhost all works fine...but... 

Is there a "better way" to deploy on IIS? I think that a good way should be to have IdSrv4 and MVC App on different server with different IP Address (so I have to configure correctly Startup.cs with different Authority and redirect Url ...I think)...  
Thanks

**Comment by digitarenet** [comment]
I deployed IdSrv4 on IIS on localhost...port 1941


But seem that Server start listening on port  26379 (random)

```
...
Content root path: C:\www\IdSrv
Now listening on: http://localhost:26379/
...
```
but I send request on 1941:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:1941/  
```

What is wrong?
This is the complete log:

```
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-3006700770-424185619-1745488364-*********-4004696415\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
Hosting environment: Production
Content root path: C:\www\IdSrv
Now listening on: http://localhost:26379/
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[1]
      Connection id "0HKS9VUNQ13I3" started.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:1941/  
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path / does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
      Request successfully matched the route with name '' and template ''.
dbug: Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler[1]
      Executing action Host.UI.Home.HomeController.Index (IdentityServer)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Host.UI.Home.HomeController.Index (IdentityServer) with arguments () - ModelState is Valid'
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Host.UI.Home.HomeController.Index (IdentityServer), returned result Microsoft.AspNetCore.Mvc.ViewResult.'
dbug: Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine[1]
      View lookup cache miss for view 'Index' in controller 'Home'.
fail: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[3]
      The view 'Index' was not found. Searched locations: ~/UI/Home/Views/Index.cshtml, ~/UI/SharedViews/Index.cshtml
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
~/UI/Home/Views/Index.cshtml
~/UI/SharedViews/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
```

**Comment by digitarenet** [comment]
I solved the problem simply deploying "UI" folder.... very easy

**Comment by rodchenkov** [comment]
You are right, I also publish my solution on stackoverflow
http://stackoverflow.com/questions/37257043/identityserver-4-using-iis

**Comment by digitarenet** [comment]
Yes, this is the best way:

```
"publishOptions": {
  "include": [
    "wwwroot",
    "UI",
    "damienbodserver.pfx",
    "web.config"
  ]}
```
