### ISSUE TITLE
Run clients raise error “An error occurred while sending the request”

### ISSUE THREAD

**Issue by Cuiqs76** [IdentityServer/IdentityServer4.Samples#42]
I set SampleApi and Console ResourceOwner Flow as startup projects. but throw a error at Line 
`return client.RequestResourceOwnerPasswordAsync("bob", "bob", "api1 api2", optional).Result;`

error: An error occurred while sending the request

**Comment by leastprivilege** [comment]
Well - this does not help a lot. You need to debug and inspect inner exceptions.

**Comment by Cuiqs76** [comment]
System.AggregateException
  HResult=-2146233088
  Message=One or more errors occurred. (An error occurred while sending the request.)
  Source=System.Private.CoreLib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at ConsoleResourceOwnerFlow.Program.RequestToken() in E:\Sample\IdentityServer4.Samples-dev\Clients\src\ConsoleResourceOwnerFlow\Program.cs:line 37
       at ConsoleResourceOwnerFlow.Program.Main(String[] args) in E:\Sample\IdentityServer4.Samples-dev\Clients\src\ConsoleResourceOwnerFlow\Program.cs:line 16
  InnerException: 
       HResult=-2147012867
       Message=An error occurred while sending the request.
       Source=System.Private.CoreLib
       StackTrace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at IdentityModel.Client.TokenClient.<RequestAsync>d__21.MoveNext()
       InnerException: 
            HResult=-2147012867
            Message=can not link to server
            NativeErrorCode=12029
            Source=System.Private.CoreLib
            StackTrace:
                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                 at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
            InnerException:

**Comment by leastprivilege** [comment]
the real cause seems to be "can not link to server". Not sure what that means. Is your server running - on the expected port etc.

**Comment by Cuiqs76** [comment]
could the code below in sampleapi  start the identity server ?  I do not change any code  of the sample but only set startup projects.

` app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:1941",
                RequireHttpsMetadata = false,

                EnableCaching = true,

                ScopeName = "api1",
                ScopeSecret = "secret",
                AutomaticAuthenticate = true
            });`

**Comment by leastprivilege** [comment]
no - IdentityServer is in a separate solution.

**Comment by Cuiqs76** [comment]
So i need to start the identittyserver for testing the clients?

**Comment by leastprivilege** [comment]
yes
